"""
02_sequential_synthesis.py
==========================
Chapter 9: Synthetic Data Generation for Federal Statistics

Implements the full sequential regression synthesis algorithm on the confidential
microdata generated by 01_confidential_dataset.py. Each variable is modeled
conditionally on previously synthesized variables; new records are sampled from
those fitted models.

Why this matters:
    Sequential synthesis is the dominant method in federal statistical agencies
    because it is transparent, auditable, and requires only standard regression
    tools. Every step can be explained to oversight bodies. This script makes
    the synthesis loop concrete and repeatable.

Synthesis order:
    1. age     - sampled from fitted marginal normal distribution
    2. educ    - logistic regression: educ | age
    3. region  - multinomial logistic regression: region | age, educ
    4. income  - linear regression on log scale + residual noise: income | age, educ, region
    5. married - logistic regression: married | age, educ, income

Usage:
    python 02_sequential_synthesis.py
    (Run 01_confidential_dataset.py first to generate confidential_microdata.csv)

Outputs:
    - Comparison of means and standard deviations printed to stdout
    - synthetic_data.csv saved to current directory (used by later scripts)

Requirements:
    Python 3.9+, numpy, pandas, scikit-learn
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import LabelEncoder


def synthesize_dataset(df_conf: pd.DataFrame, n_synth: int = 600, random_state: int = 2025) -> pd.DataFrame:
    """
    Synthesize a new dataset using sequential regression synthesis.

    Each variable is modeled on the *confidential* data, then new values are
    sampled from the fitted predictive distribution using the *synthetic* values
    of previously synthesized variables as predictors. No confidential record
    values are copied directly.

    Parameters
    ----------
    df_conf : pd.DataFrame
        Confidential microdata with columns: age, educ, region, married, income.
    n_synth : int
        Number of synthetic records to generate.
    random_state : int
        Random seed for reproducibility.

    Returns
    -------
    pd.DataFrame
        Synthetic dataset with the same columns as df_conf.
    """
    rng = np.random.default_rng(random_state)
    synth = {}

    # ------------------------------------------------------------------
    # Step 1: Synthesize age from marginal distribution
    # Fit a normal distribution to confidential ages, then sample.
    # We do not condition on anything — age is the root variable.
    # ------------------------------------------------------------------
    age_mean = df_conf["age"].mean()
    age_std = df_conf["age"].std()
    synth_age = rng.normal(age_mean, age_std, n_synth)
    synth_age = np.clip(np.round(synth_age), 18, 80).astype(int)
    synth["age"] = synth_age

    # ------------------------------------------------------------------
    # Step 2: Synthesize education conditional on age
    # Education is categorical, so we use multinomial logistic regression.
    # The model learns P(educ | age) from confidential data; we sample from
    # those probabilities for each synthetic age value.
    # ------------------------------------------------------------------
    le_educ = LabelEncoder()
    educ_enc = le_educ.fit_transform(df_conf["educ"])
    lr_educ = LogisticRegression(max_iter=500, random_state=random_state)
    lr_educ.fit(df_conf[["age"]], educ_enc)
    educ_probs = lr_educ.predict_proba(synth_age.reshape(-1, 1))
    synth_educ_enc = np.array([rng.choice(len(p), p=p) for p in educ_probs])
    synth["educ"] = le_educ.inverse_transform(synth_educ_enc)

    # ------------------------------------------------------------------
    # Step 3: Synthesize region conditional on age and education
    # Region is also categorical; multinomial logistic using both predictors.
    # ------------------------------------------------------------------
    le_reg = LabelEncoder()
    reg_enc = le_reg.fit_transform(df_conf["region"])
    lr_reg = LogisticRegression(max_iter=500, random_state=random_state)
    lr_reg.fit(df_conf[["age", "educ"]], reg_enc)
    X_reg = np.column_stack([synth_age, synth["educ"]])
    reg_probs = lr_reg.predict_proba(X_reg)
    synth_reg_enc = np.array([rng.choice(len(p), p=p) for p in reg_probs])
    synth["region"] = le_reg.inverse_transform(synth_reg_enc)

    # ------------------------------------------------------------------
    # Step 4: Synthesize income conditional on age, education, and region
    # Income is continuous; we use linear regression on log-income to handle
    # the right-skewed distribution. We add random noise drawn from the
    # residual distribution to preserve variability.
    # ------------------------------------------------------------------
    region_enc = LabelEncoder().fit_transform(df_conf["region"])
    lr_inc = LinearRegression()
    X_inc = np.column_stack([
        df_conf["age"].values,
        df_conf["educ"].values,
        region_enc,
    ])
    log_income_conf = np.log(np.maximum(df_conf["income"].values, 1))
    lr_inc.fit(X_inc, log_income_conf)
    residuals = log_income_conf - lr_inc.predict(X_inc)
    res_std = residuals.std()

    synth_region_enc = LabelEncoder().fit(df_conf["region"]).transform(synth["region"])
    X_synth_inc = np.column_stack([synth_age, synth["educ"], synth_region_enc])
    pred_log_income = lr_inc.predict(X_synth_inc)
    noise = rng.normal(0, res_std, n_synth)
    synth["income"] = np.clip(np.exp(pred_log_income + noise), 5000, 300000).astype(int)

    # ------------------------------------------------------------------
    # Step 5: Synthesize married conditional on age, education, and income
    # Binary outcome; logistic regression. Income is included because the
    # confidential data shows a positive correlation between income and
    # being married, likely reflecting life-stage and selection effects.
    # ------------------------------------------------------------------
    lr_mar = LogisticRegression(max_iter=500, random_state=random_state)
    X_mar = df_conf[["age", "educ", "income"]].values
    lr_mar.fit(X_mar, df_conf["married"].values)
    X_synth_mar = np.column_stack([synth_age, synth["educ"], synth["income"]])
    married_probs = lr_mar.predict_proba(X_synth_mar)[:, 1]
    synth["married"] = rng.binomial(1, married_probs)

    return pd.DataFrame(synth)


def print_comparison(df_conf: pd.DataFrame, df_synth: pd.DataFrame) -> None:
    """Print mean and standard deviation comparison for numeric variables."""
    print("Comparison: confidential vs. synthetic dataset")
    print("=" * 65)
    print(f"{'Variable':<12} {'Conf Mean':>12} {'Synth Mean':>12} {'Conf Std':>10} {'Synth Std':>10}")
    print("-" * 65)
    for col in ["age", "educ", "income", "married"]:
        cm = df_conf[col].mean()
        sm = df_synth[col].mean()
        cs = df_conf[col].std()
        ss = df_synth[col].std()
        print(f"{col:<12} {cm:>12.2f} {sm:>12.2f} {cs:>10.2f} {ss:>10.2f}")

    print()
    print("Region distribution comparison:")
    conf_region = df_conf["region"].value_counts(normalize=True).sort_index()
    synth_region = df_synth["region"].value_counts(normalize=True).sort_index()
    for reg in conf_region.index:
        cr = conf_region.get(reg, 0)
        sr = synth_region.get(reg, 0)
        print(f"  {reg:<10}: conf={cr:.3f}  synth={sr:.3f}")


if __name__ == "__main__":
    import os

    conf_path = "confidential_microdata.csv"
    if not os.path.exists(conf_path):
        print(f"ERROR: {conf_path} not found. Run 01_confidential_dataset.py first.")
        raise SystemExit(1)

    df_conf = pd.read_csv(conf_path)
    print(f"Loaded confidential microdata: {df_conf.shape}")

    print("\nRunning sequential regression synthesis (n=600, seed=2025)...")
    df_synth = synthesize_dataset(df_conf, n_synth=600, random_state=2025)

    print(f"Synthesized {len(df_synth)} records.")
    print("\nSynthetic dataset head (first 8 records):")
    print(df_synth.head(8).to_string(index=False))
    print("\nNo row in the synthetic dataset corresponds to any real person.")
    print("The synthesizer learned the joint distribution; these are new samples.")

    print()
    print_comparison(df_conf, df_synth)

    df_synth.to_csv("synthetic_data.csv", index=False)
    print("\nSaved: synthetic_data.csv")
